import { uid } from "./utils.js";

export function createDefaultState() {
  return {
    accounts: [
      {
        id: uid("acc"),
        name: "Cash",
        type: "cash",
        currencySymbol: "$",
        openingBalance: 0,
        includeInTotalBalance: true,
        color: "#19c6a7",
        icon: "cash",
        notes: "Physical cash account",
      },
      {
        id: uid("acc"),
        name: "Main Bank",
        type: "bank",
        currencySymbol: "$",
        openingBalance: 0,
        includeInTotalBalance: true,
        color: "#7db8ff",
        icon: "bank",
        notes: "Primary checking account",
      },
      {
        id: uid("acc"),
        name: "Savings",
        type: "savings",
        currencySymbol: "$",
        openingBalance: 0,
        includeInTotalBalance: true,
        color: "#ffb84d",
        icon: "safe",
        notes: "Savings reserve",
      },
    ],
    categories: [
      {
        id: "groceries",
        name: "Groceries",
        type: "expense",
        icon: "cart",
        color: "#19c6a7",
        subcategories: ["Supermarket", "Produce", "Household"],
        budgetLimit: 500,
        budgetPeriod: "monthly",
      },
      {
        id: "dining",
        name: "Dining",
        type: "expense",
        icon: "food",
        color: "#ff8f6b",
        subcategories: ["Dining Out", "Coffee", "Delivery"],
        budgetLimit: 160,
        budgetPeriod: "weekly",
      },
      {
        id: "transport",
        name: "Transport",
        type: "expense",
        icon: "travel",
        color: "#00a6c7",
        subcategories: ["Fuel", "Taxi", "Public Transit"],
        budgetLimit: 220,
        budgetPeriod: "monthly",
      },
      {
        id: "utilities",
        name: "Utilities",
        type: "expense",
        icon: "spark",
        color: "#6f8cff",
        subcategories: ["Internet", "Electricity", "Water", "Gas"],
        budgetLimit: 280,
        budgetPeriod: "monthly",
      },
      {
        id: "housing",
        name: "Housing",
        type: "expense",
        icon: "home",
        color: "#48b29c",
        subcategories: ["Rent", "Repairs", "Furniture"],
        budgetLimit: 1800,
        budgetPeriod: "monthly",
      },
      {
        id: "health",
        name: "Health",
        type: "expense",
        icon: "health",
        color: "#ef6461",
        subcategories: ["Doctor", "Medicine", "Insurance"],
        budgetLimit: 200,
        budgetPeriod: "monthly",
      },
      {
        id: "shopping",
        name: "Shopping",
        type: "expense",
        icon: "gift",
        color: "#f06f9b",
        subcategories: ["Clothing", "Personal Care", "Gadgets"],
        budgetLimit: 300,
        budgetPeriod: "monthly",
      },
      {
        id: "entertainment",
        name: "Entertainment",
        type: "expense",
        icon: "spark",
        color: "#9f86ff",
        subcategories: ["Streaming", "Games", "Events"],
        budgetLimit: 120,
        budgetPeriod: "monthly",
      },
      {
        id: "salary",
        name: "Salary",
        type: "income",
        icon: "briefcase",
        color: "#19c6a7",
        subcategories: ["Payroll", "Bonus", "Commission"],
        budgetLimit: 0,
        budgetPeriod: "monthly",
      },
      {
        id: "freelance",
        name: "Freelance",
        type: "income",
        icon: "briefcase",
        color: "#00a6c7",
        subcategories: ["Consulting", "Project Payment", "Invoice"],
        budgetLimit: 0,
        budgetPeriod: "monthly",
      },
      {
        id: "refund",
        name: "Refund",
        type: "income",
        icon: "arrow-down",
        color: "#48b29c",
        subcategories: ["Rebate", "Cashback", "Returned Item"],
        budgetLimit: 0,
        budgetPeriod: "monthly",
      },
    ],
    transactions: [],
  };
}
